import type { Metadata } from "next";
import "./globals.css";
import FooterClient from "@/components/Footer/FooterClient";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Bytezone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body className="bg-gradient-to-b from-purple-500 to-purple-50 min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-grow ">{children}</main>

        <footer className="bg-purple-900">
          <FooterClient />
        </footer>
      </body>
    </html>
  );
}
